include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - template/ansible-role.gitlab-ci.yaml # ToDo: remove this line post merge of nofusscomputing/projects/gitlab-ci!33
      - template/automagic.gitlab-ci.yaml

variables:
  MY_PROJECT_ID: "46743174"
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/ansible_role_docker_management.git"
  PAGES_ENVIRONMENT_PATH: projects/docker_management/


Ansible-roles.Submodule.Deploy:
  extends: .submodule_update_trigger
  variables:
    SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/ansible-roles
