INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Ansible-EE
repo_url: https://gitlab.com/nofusscomputing/projects/ansible/docker_management
edit_uri: '/-/ide/project/nofusscomputing/projects/ansible/docker_management/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Ansible Roles:

    - Docker Management:

      - projects/docker_management/index.md

- Operations: 

  - operations/index.md

- Contact Us: contact.md

