---
- name: Install Docker
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  become: true
  notify: restart docker
  when: ansible_distribution in ['Debian', 'Ubuntu']
  register: docker_management_install
  run_once: true
  tags:
    - docker_installation


- name: Start Docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
