---
- name: Fetch Docker repository signing key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /usr/share/keyrings/docker.asc
    mode: '644'
    owner: root
    group: root
  when:
    - ansible_os_family == 'Debian'


- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] http://download.docker.com/linux/{{ ansible_distribution | lower }}   {{ ansible_distribution_release | lower }} stable"
    state: present
    filename: "docker"
  when:
    - ansible_os_family == 'Debian'


- name: Install Docker
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  become: true
  notify: restart docker
  when: ansible_distribution in ['Debian', 'Ubuntu']
  register: docker_management_install
  run_once: true
  tags:
    - docker_installation


- name: Start Docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
