---
- name: Manage Docker Containers
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: "{{ item.state | default('present') }}"
    command: "{{ item.command | default(omit) }}"
    comparisons: "{{ item.comparisons | default(omit) | from_yaml }}"
    entrypoint: "{{ item.entrypoint | default(omit) }}"
    ports: "{{ item.ports | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    environment: "{{ item.environment | default(omit) }}"
    restart_policy: "{{ item.restart_policy | default(omit) }}"
    restart_retries: "{{ item.restart_retries | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    log_driver: "{{ item.log_driver | default(omit) }}"
    log_options: "{{ item.log_options | default(omit) }}"
    healthcheck: "{{ item.healthcheck | default(omit) }}"
    depends_on: "{{ item.depends_on | default(omit) }}"
    cap_drop: "{{ item.cap_drop | default(omit) }}"
    cap_add: "{{ item.cap_add | default(omit) }}"
    privileged: "{{ item.privileged | default(false) }}"
    network_mode: "{{ item.network_mode | default(omit) }}"
    networks: "{{ item.networks | default(omit) }}"
    dns_servers: "{{ item.dns_servers | default(omit) }}"
    dns_search_domains: "{{ item.dns_search_domains | default(omit) }}"
    user: "{{ item.user | default(omit)  }}"
  loop: "{{ docker_containers | from_yaml }}"
  tags:
    - docker_containers
