---
- name: Manage Docker Images
  community.docker.docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    source: "{{ item.source }}"
    pull: "{{ item.pull }}"
    build:
      path: "{{ item.build.path }}"
      pull: "{{ item.build.pull }}"
      nocache: "{{ item.build.nocache }}"
      buildargs: "{{ item.build.buildargs }}"
      labels: "{{ item.build.labels }}"
    push: "{{ item.push }}"
    force_source: "{{ item.force_source }}"
    force: "{{ item.force }}"
    remove: "{{ item.remove }}"
    source_directory: "{{ item.source_directory }}"
  loop: "{{ docker_images }}"
  tags:
    - docker_images
