---
- name: Manage Docker Containers
  community.docker.docker_container:
    name: "{{ item.name }}"
    hostname: "{% if item.hostname is defined %}{{ item.hostname }}{% else %}{{ item.name | lower | replace(' ', '') }}{% endif %}"
    domainname: "{{ item.domainname | default(omit) }}"
    image: "{{ item.image }}"
    state: "{{ item.state | default('started') }}"
    command: "{{ item.command | default(omit) }}"
    comparisons: "{{ item.comparisons | default(docker_container_comparisons_default) | from_yaml }}"
    entrypoint: "{{ item.entrypoint | default(omit) }}"
    exposed_ports: "{{ item.exposed_ports | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    env: "{{ item.env | default(omit) | from_yaml }}"
    restart_policy: "{{ item.restart_policy | default('always') }}"
    restart_retries: "{{ item.restart_retries | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    log_driver: "{{ itemz.log_driver | default(omit) }}"
    log_options: "{{ item.log_options | default(omit) }}"
    healthcheck: "{{ item.healthcheck | default(omit) }}"
    # depends_on: "{{ item.depends_on | default(omit) | from_yaml }}"
    cap_drop: "{{ item.cap_drop | default(omit) }}"
    cap_add: "{{ item.cap_add | default(omit) }}"
    privileged: "{{ item.privileged | default(false) }}"
    published_ports: "{{ item.published_ports | default(omit) | from_yaml }}"
    network_mode: "{{ item.network_mode | default(omit) }}"
    networks: "{{ item.networks | default(omit) }}"
    dns_servers: "{{ item.dns_servers | default(omit) }}"
    dns_search_domains: "{{ item.dns_search_domains | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    tty: "{{ item.tty | default(omit) }}"
  loop: "{{ docker_containers | default('') | from_yaml }}"
  diff: false # May show env vars that are secrets
  no_log: true
