---
- name: Manage Docker Containers
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: "{{ item.state }}"
    command: "{{ item.command }}"
    entrypoint: "{{ item.entrypoint }}"
    ports: "{{ item.ports }}"
    volumes: "{{ item.volumes }}"
    environment: "{{ item.environment }}"
    restart_policy: "{{ item.restart_policy }}"
    restart_retries: "{{ item.restart_retries }}"
    labels: "{{ item.labels }}"
    log_driver: "{{ item.log_driver }}"
    log_options: "{{ item.log_options }}"
    healthcheck: "{{ item.healthcheck }}"
    depends_on: "{{ item.depends_on }}"
    cap_drop: "{{ item.cap_drop }}"
    cap_add: "{{ item.cap_add }}"
    privileged: "{{ item.privileged }}"
    network_mode: "{{ item.network_mode }}"
    networks: "{{ item.networks }}"
    dns_servers: "{{ item.dns_servers }}"
    dns_search_domains: "{{ item.dns_search_domains }}"
  loop: "{{ docker_containers }}"
  tags:
    - docker_containers
